fragment OrderProductBase on Order {
	date
	orderNumber
	total
	status
	lineItems {
		nodes {
			quantity
			total
			product {
				node {
					...SimpleProductFragment
					...VariableProductFragment
				}
			}
		}
	}
}
