query GetProductsWithCategories {
	products(first: 200) {
		nodes {
			...ProductMinBase
			productCategories {
				nodes {
					...ProductCategoryBase
					ancestors {
						nodes {
							name
							slug
						}
					}
				}
			}
		}
	}
}
