query GetProductsByCategory(
	$field: ProductsOrderByEnum!
	$order: OrderEnum!
	$categories: [String]!
	$first: Int
	$last: Int
	$after: String
	$before: String
) {
	products(
		where: { orderby: { field: $field, order: $order }, categoryIn: $categories }
		first: $first
		last: $last
		after: $after
		before: $before
	) {
		nodes {
			...ProductMinBase
			image {
				...ImageBase
			}
			productCategories {
				nodes {
					id
					slug
					name
				}
			}
			...ProductPriceBase
			shortDescription
		}
		pageInfo {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
		}
	}
}
